---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sample.gosarami.github.io
  resources:
  - sampledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.gosarami.github.io
  resources:
  - sampledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - sample.gosarami.github.io
  resources:
  - sampledeployments/status
  verbs:
  - get
  - patch
  - update
