# permissions for end users to edit sampledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sampledeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample-deployment
    app.kubernetes.io/part-of: sample-deployment
    app.kubernetes.io/managed-by: kustomize
  name: sampledeployment-editor-role
rules:
- apiGroups:
  - sample.gosarami.github.io
  resources:
  - sampledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.gosarami.github.io
  resources:
  - sampledeployments/status
  verbs:
  - get
